const posts=[
{id:1,cat:"fps",title:"How to Increase FPS in Low-End PC Games: 15 Settings That Actually Matter",desc:"A practical checklist covering resolution, shadows, upscaling, background apps and bottleneck checks.",date:"September 15, 2026"},
{id:2,cat:"fixes",title:"How to Reduce FPS Drops and Stuttering in PC Games",desc:"Learn how to identify common causes of stutter before changing random settings.",date:"September 15, 2026"},
{id:3,cat:"igpu",title:"Best Games for Intel UHD Graphics: What to Check Before You Play",desc:"A guide to judging game requirements and choosing sensible settings for Intel integrated graphics.",date:"September 15, 2026"},
{id:4,cat:"upscaling",title:"720p vs 900p vs 1080p Gaming on a Low-End PC",desc:"Understand the trade-off between rendering resolution, clarity and GPU workload.",date:"September 15, 2026"},
{id:5,cat:"games",title:"25 Open-World Games for Low-End PCs: How to Check Compatibility",desc:"A framework for evaluating low-spec open-world games without relying on misleading FPS promises.",date:"September 15, 2026"}
];

const categoryNames={fps:"FPS Optimization",igpu:"Integrated Graphics",fixes:"PC Fixes",games:"Low-Spec Games",upscaling:"Resolution & Upscaling"};

function cards(items){return items.map(p=>`<a class="card" href="article.html?id=${p.id}"><span class="pill">${categoryNames[p.cat]}</span><h3>${p.title}</h3><p>${p.desc}</p><small>${p.date}</small></a>`).join("")}
function renderPosts(items=posts){const el=document.getElementById("posts");if(el)el.innerHTML=cards(items)}
function searchPosts(){const q=document.getElementById("search").value.toLowerCase();renderPosts(posts.filter(p=>(p.title+" "+p.desc+" "+p.cat).toLowerCase().includes(q)))}
function loadCategory(){const q=new URLSearchParams(location.search).get("cat")||"fps";document.getElementById("title").textContent=categoryNames[q]||"Guides";document.getElementById("list").innerHTML=cards(posts.filter(p=>p.cat===q))}
function loadArticle(){const id=Number(new URLSearchParams(location.search).get("id"))||1;const p=posts.find(x=>x.id===id)||posts[0];document.title=p.title+" | LowSpec Gaming Hub";document.getElementById("article").innerHTML=articleContent(p)}
function articleContent(p){if(p.id===1)return `<span class="pill">${categoryNames[p.cat]}</span><h1>${p.title}</h1><p><small>Updated: ${p.date}</small></p><p>Low-end PC par FPS improve karne ka best tareeqa random “FPS booster” install karna nahi hai. Pehle bottleneck identify karo, phir settings ko step-by-step test karo.</p><h2>1. Start With Your Resolution</h2><p>GPU usage high ho to 1080p se 900p ya 720p par test karo. Resolution kam karne se GPU ko fewer pixels render karne padte hain.</p><h2>2. Lower Shadows and Reflections</h2><p>Shadows, reflections aur ambient-occlusion jaise settings ko Medium ya Low par test karo. Har game mein performance impact different hota hai.</p><h2>3. Try Resolution Scaling</h2><p>Agar game mein render scale available hai, 70–90% range se test kar sakte ho. Image quality aur FPS ke beech balance choose karo.</p><h2>4. Use FSR or XeSS When Available</h2><p>Supported games mein upscaling lower internal resolution render karke output ko higher display resolution par reconstruct kar sakti hai. Quality modes se start karna usually sensible hai.</p><h2>5. Check Background Apps</h2><p>Unnecessary browser tabs, recording tools aur background applications CPU, RAM ya storage resources consume kar sakte hain.</p><h2>6. Find the Bottleneck</h2><table><tr><th>Observation</th><th>Possible issue</th></tr><tr><td>GPU near 100%</td><td>GPU bottleneck</td></tr><tr><td>CPU heavily loaded</td><td>CPU bottleneck</td></tr><tr><td>RAM almost full</td><td>Memory pressure</td></tr><tr><td>Very high temperatures</td><td>Possible thermal throttling</td></tr></table><h2>7. Test One Change at a Time</h2><p class="note">Before/after FPS note karo. Agar possible ho to same location, same resolution and same settings use karke average FPS aur 1% lows record karo.</p><h2>What Not to Do</h2><ul><li>Fake benchmark numbers publish mat karo.</li><li>Unknown “FPS booster” software recommend mat karo.</li><li>Config files edit karne se pehle backup rakho.</li><li>“100% FPS boost” jaise guarantees avoid karo.</li></ul><h2>Conclusion</h2><p>Low-end PC optimization ka goal realistic settings aur stable gameplay hai. Resolution, shadows, upscaling aur bottleneck identification se start karo, phir game-specific testing karo.</p>`;return `<span class="pill">${categoryNames[p.cat]}</span><h1>${p.title}</h1><p><small>Updated: ${p.date}</small></p><p>${p.desc}</p><h2>Before You Start</h2><p>Check your CPU, GPU or integrated graphics, RAM, storage and the game's official system requirements.</p><h2>Practical Approach</h2><p>Change one setting at a time and compare performance under the same conditions. Avoid guarantees because performance varies by hardware and game version.</p><h2>Conclusion</h2><p>Use measured settings and real testing rather than generic optimization claims.</p>`}
function toggleMenu(){const n=document.getElementById("nav");n.style.display=n.style.display==="flex"?"none":"flex"}
renderPosts();
